import * as THREE from 'three';
import { joinRoom } from '@trystero-p2p/mqtt';
import './style.css';

const COURSES = [
  { id:'canyon', name:'Canyon de glace', tag:'CLASSIQUE', length:520, color:'#70dceb', bank:'#839aa7', ice:'#d0f6fb', sky:0x9ed9ec, twist:1, hazards:[76,119,164,216,268,318,371,426,470] },
  { id:'pines', name:'Forêt de sapins', tag:'TECHNIQUE', length:590, color:'#69b9cc', bank:'#4b7968', ice:'#a9d5c7', sky:0x8fc4bc, twist:1.5, hazards:[61,101,144,194,243,289,335,383,429,481,527] },
  { id:'summit', name:'Pic enneigé', tag:'EXTRÊME', length:650, color:'#a1e5f3', bank:'#758999', ice:'#e3f8fb', sky:0xb0d9ef, twist:1.9, hazards:[52,86,124,170,218,267,310,357,404,452,501,552,600] }
];
const params = new URLSearchParams(location.search);
const initialCourse = COURSES.find(c=>c.id===params.get('course')) || COURSES[0];
const initialRoom = (params.get('room')||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);
const app = document.querySelector('#app');
app.innerHTML = `
  <div id="game" aria-label="Jeu de course de bateau en 3D"></div>
  <header class="top"><div class="brand"><span class="brand-mark">◆</span><span>BLOCK<span class="brand-accent">BOAT</span><small>BOAT RUN 3D</small></span></div><div class="top-right"><span class="online-dot"></span><span id="online-label">PRÊT À GLISSER</span><button id="sound" class="icon-btn" aria-label="Activer ou couper le son">♪</button></div></header>
  <main>
    <section id="menu" class="menu" aria-label="Menu de course">
      <div class="eyebrow"><span class="line"></span> LE RUN COMMENCE ICI <span class="line"></span></div>
      <h1>CHOISIS TA <em>PISTE.</em></h1><p class="intro">Dévale la rivière. Esquive les blocs. Bats le chrono.</p>
      <div id="course-list" class="course-list"></div>
      <div class="menu-actions"><button id="play" class="primary">JOUER EN SOLO <span>↗</span></button><button id="multiplayer" class="secondary">COURSE ENTRE AMIS <span>◎</span></button></div>
      <div class="controls-hint"><span>← → / A D</span> diriger sur ordinateur <i>•</i> <span>TOUCHES À L'ÉCRAN</span> sur téléphone</div>
    </section>
    <section id="lobby" class="panel hidden" aria-label="Salon multijoueur"><button class="back" id="back-lobby">← RETOUR</button><div class="panel-label">COURSE ENTRE AMIS</div><h2>UN CODE.<br><em>TOUT LE MONDE JOUE.</em></h2><p>Choisissez la même piste et partagez le code ou le lien avec vos amis.</p><div class="room-box"><label for="room-code">CODE DU SALON</label><div class="room-input"><input id="room-code" maxlength="6" autocomplete="off" autocapitalize="characters" spellcheck="false" placeholder="EX : BOAT42"/><button id="random-room" title="Créer un code">↻</button></div></div><div class="lobby-buttons"><button class="primary" id="join-room">REJOINDRE LE SALON <span>↗</span></button><button class="secondary hidden" id="copy-link">COPIER LE LIEN ⧉</button></div><div id="lobby-status" class="lobby-status">Aucun salon rejoint</div><div id="players" class="players"></div><button id="race-together" class="race-button hidden">LANCER MA COURSE →</button><p class="small-note">Chaque joueur lance sa course quand il est prêt. Les bateaux connectés apparaissent sur la piste en direct.</p></section>
    <section id="hud" class="hud hidden" aria-label="Statistiques de course"><div class="hud-top"><div class="hud-item"><span>CHRONO</span><strong id="timer">00:00.00</strong></div><div class="hud-item progress-block"><span>PROGRESSION</span><strong id="progress">0%</strong><div class="meter"><div id="meter-fill"></div></div></div><button id="pause" class="hud-pause" aria-label="Mettre en pause">Ⅱ</button></div><div id="countdown" class="countdown"></div><div id="toast" class="toast"></div><div class="hud-bottom"><div class="speed"><strong id="speed">0</strong><span>BLOCS/S</span></div><div id="position" class="position">PISTE 01 / 03</div></div><div class="touch-controls"><button id="left" aria-label="Tourner à gauche">◀</button><button id="right" aria-label="Tourner à droite">▶</button></div></section>
    <section id="pause-panel" class="modal hidden"><div class="modal-inner"><div class="panel-label">PAUSE</div><h2>ON SOUFFLE ?</h2><button id="resume" class="primary">REPRENDRE →</button><button id="quit" class="secondary">QUITTER LA COURSE</button></div></section>
    <section id="results" class="modal hidden"><div class="modal-inner"><div class="panel-label">COURSE TERMINÉE</div><h2>RUN <em>TERMINÉ !</em></h2><div class="result-stat"><span>TON TEMPS</span><strong id="final-time">00:00.00</strong></div><div class="result-stat"><span>MEILLEUR TEMPS SUR CET APPAREIL</span><strong id="best-time">—</strong></div><div id="finishers" class="finishers"></div><button id="retry" class="primary">REJOUER →</button><button id="home" class="secondary">CHOISIR UNE PISTE</button></div></section>
  </main><div class="vignette"></div>`;

let selected = initialCourse, scene, camera, renderer, boat, boatGroup, world, river, scenery = [], obstacles = [], remoteBoats = new Map();
let state='menu', room=null, sendState=null, sendFinish=null, sendHello=null, roomId='', peers=new Map(), held={left:false,right:false}, x=0, z=0, vx=0, speed=0, elapsed=0, lastTime=performance.now(), countdown=0, networkClock=0, collisions=0, toastUntil=0, muted=true, audioCtx;
const $=id=>document.getElementById(id);
const clamp=(a,min,max)=>Math.min(max,Math.max(min,a));
const rand=(seed)=>{let n=Math.sin(seed*127.1+78.233)*43758.5453;return n-Math.floor(n)};
const path=(v,c=selected)=>Math.sin(v*.022)*3.3*c.twist + Math.sin(v*.047)*1.15*c.twist;
const groundY=v=>-v*.047;
const formatTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}.${String(Math.floor(s*100)%100).padStart(2,'0')}`;
const mat=(color,roughness=1)=>new THREE.MeshStandardMaterial({color,roughness,flatShading:true});
const block=(w,h,d,m)=>{let mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.castShadow=true;mesh.receiveShadow=true;return mesh};
function label(t){return t.replace(/[&<>"']/g,'')}
function renderCourses(){ $('course-list').innerHTML=COURSES.map((c,i)=>`<button class="course-card ${c===selected?'selected':''}" data-course="${c.id}" aria-pressed="${c===selected}"><span class="course-no">0${i+1}</span><span class="course-detail"><strong>${c.name}</strong><small>${c.length} BLOCS <b>•</b> ${c.tag}</small></span><span class="course-arrow">↗</span></button>`).join('');document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{selected=COURSES.find(c=>c.id===b.dataset.course);renderCourses();buildWorld();$('position').textContent=`PISTE 0${COURSES.indexOf(selected)+1} / 03`;if(room){leaveRoom();$('lobby-status').textContent='Piste modifiée. Rejoins le salon pour continuer.'}})}
function init3D(){scene=new THREE.Scene();scene.background=new THREE.Color(selected.sky);scene.fog=new THREE.Fog(selected.sky,40,190);camera=new THREE.PerspectiveCamera(63,innerWidth/innerHeight,.1,270);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.3:1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=innerWidth>700;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;$('game').append(renderer.domElement);let sun=new THREE.DirectionalLight(0xfff2cc,2.8);sun.position.set(-35,70,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-100;sun.shadow.camera.right=100;sun.shadow.camera.top=100;sun.shadow.camera.bottom=-100;sun.shadow.normalBias=.04;scene.add(sun,new THREE.AmbientLight(0xc4eafa,1.25));world=new THREE.Group();scene.add(world);boatGroup=createBoat('#f4a442',true);scene.add(boatGroup);buildWorld();camera.position.set(13,19,-19);camera.lookAt(0,0,13);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
function createBoat(color,player=false){const g=new THREE.Group(),wood=mat(color),dark=mat('#4c2c24'),edge=mat('#e7ba70'),white=mat('#fff5d6');let hull=block(2.0,.48,3.2,wood);hull.position.y=.44;g.add(hull);let bow=block(1.65,.38,.58,wood);bow.position.set(0,.43,1.75);g.add(bow);let stern=block(1.65,.4,.38,wood);stern.position.set(0,.43,-1.68);g.add(stern);for(let s of [-1,1]){let rail=block(.22,.36,2.95,edge);rail.position.set(s*.94,.78,0);g.add(rail)}let seat=block(1.6,.12,.35,dark);seat.position.set(0,.78,-.35);g.add(seat);if(player){let head=block(.55,.58,.53,mat('#f6c493'));head.position.set(0,1.49,-.35);g.add(head);let torso=block(.8,.52,.62,mat('#36a7bf'));torso.position.set(0,1.0,-.35);g.add(torso)}else{let flag=block(.85,.12,.14,white);flag.position.set(0,1.2,-.45);g.add(flag)}g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function buildWorld(){if(!world)return;while(world.children.length)world.remove(world.children[0]);obstacles=[];scene.background.set(selected.sky);scene.fog.color.set(selected.sky);let water=mat(selected.color,.35),bank=mat(selected.bank),ice=mat(selected.ice),darkIce=mat('#486c79'),foam=mat('#d6f9ff'),rock=mat('#526674'),trunk=mat('#685345'),pine=mat('#295c59'),snow=mat('#f6ffff');
  // Short separate segments follow the snaking channel.
  for(let v=0;v<selected.length+100;v+=8){let center=path(v+4),angle=Math.atan2(path(v+8)-path(v),8),group=new THREE.Group();group.position.set(center,groundY(v+4),v+4);group.rotation.y=angle;let waterPiece=block(15,.35,8.25,water);waterPiece.position.y=-.1;group.add(waterPiece);for(let side of [-1,1]){let lip=block(2,.65,8.22,ice);lip.position.set(side*8.3,.12,0);group.add(lip);let shore=block(16,2.8,8.24,bank);shore.position.set(side*17.2,-.68,0);group.add(shore);let cap=block(16,.3,8.24,ice);cap.position.set(side*17.2,.85,0);group.add(cap)}world.add(group)}
  for(let v=12;v<selected.length;v+=17){for(let s of [-1,1]){const r=rand(v+s*987),side=s*(11.1+r*12),obj=new THREE.Group();obj.position.set(path(v)+side,groundY(v)+1.3,v);if(selected.id==='pines'){let stem=block(.55,2,.55,trunk);stem.position.y=1.0;obj.add(stem);for(let i=0;i<3;i++){let p=block(2.2-i*.4,1.35,2.2-i*.4,pine);p.position.y=2+i*.85;p.rotation.y=.785;obj.add(p)}}else{let size=1+r*2,crag=block(size,size*1.7,size, r>.5?rock:darkIce);crag.position.y=size*.65;crag.rotation.y=r*2;obj.add(crag);if(r>.46){let top=block(size*1.05,.35,size*1.05,snow);top.position.y=size*1.4;obj.add(top)}}world.add(obj)}}
  selected.hazards.forEach((v,i)=>{let offset=(rand(i*6+selected.length)-.5)*9.5, size=1.15+rand(i*3+2)*.8;let hazard=block(size,size,size,selected.id==='pines'?rock:darkIce);hazard.position.set(path(v)+offset,groundY(v)+size*.38,v);hazard.rotation.y=rand(i*12)*2;world.add(hazard);obstacles.push({x:hazard.position.x,z:v,r:size*.85,hit:false});for(let s of [-1,1]){let post=block(.25,1.8,.25,mat('#ffbc56'));post.position.set(path(v)+s*6.5,groundY(v)+.9,v);world.add(post)}});
  for(let v=6;v<selected.length;v+=10){for(let n=0;n<3;n++){let f=block(.32,.025,.65,foam);f.position.set(path(v)+(rand(v+n*19)-.5)*12,groundY(v)+.12,v+n*1.4);world.add(f)}}
  let finish=new THREE.Group();finish.position.set(path(selected.length),groundY(selected.length),selected.length);for(let s of [-1,1]){let pillar=block(.9,8,.9,mat('#182e3b'));pillar.position.set(s*7.1,4,0);finish.add(pillar)}let beam=block(15,.8,.9,mat('#edbd65'));beam.position.set(0,7.5,0);finish.add(beam);world.add(finish)
}
function sound(freq=440,secs=.08){if(muted)return;try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),gain=audioCtx.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audioCtx.currentTime);gain.gain.setValueAtTime(.05,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+secs);o.connect(gain).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+secs)}catch{}}
function show(screen){for(let id of ['menu','lobby','hud','pause-panel','results'])$(id).classList.toggle('hidden',id!==screen)}
function flash(message){$('toast').textContent=message;$('toast').classList.add('visible');toastUntil=performance.now()+1700}
function countdownStart(){state='countdown';show('hud');x=path(0);z=0;vx=0;speed=0;elapsed=0;collisions=0;obstacles.forEach(o=>o.hit=false);countdown=3.65;$('countdown').textContent='3';$('timer').textContent='00:00.00';$('progress').textContent='0%';$('meter-fill').style.width='0%';boatGroup.visible=true;sound(510)}
function finish(){state='finished';show('results');$('final-time').textContent=formatTime(elapsed);let key='blockboat-best-'+selected.id,prior=Number(localStorage.getItem(key))||Infinity;if(elapsed<prior){localStorage.setItem(key,String(elapsed));prior=elapsed}$('best-time').textContent=formatTime(prior);$('finishers').textContent='';if(room)try{sendFinish({time:elapsed,course:selected.id})}catch{};sound(810,.25)}
function resetMenu(){state='menu';show('menu');$('countdown').textContent='';boatGroup.visible=true;renderCourses()}
function updateBoatPosition(group,bx,bz,lean=0){group.position.set(bx,groundY(bz)+.1,bz);group.rotation.z=lean;group.rotation.y=-Math.atan2(path(bz+2)-path(bz-2),4)*.25;group.rotation.x=Math.sin(performance.now()*.006+bz)*.018}
function animate(t){requestAnimationFrame(animate);const dt=Math.min((t-lastTime)/1000,.05);lastTime=t;
 if(state==='countdown'){countdown-=dt;let numeral=Math.ceil(countdown);$('countdown').textContent=numeral>0?String(numeral):'GO !';if(countdown<=-.35){state='running';$('countdown').textContent='';sound(750,.18)}else if(numeral>0&&numeral!==Math.ceil(countdown+dt))sound(520)}
 if(state==='running'){elapsed+=dt;let steer=(held.right?1:0)-(held.left?1:0);vx+=(steer*21-vx*4.2)*dt;x+=vx*dt;let center=path(z),outside=Math.abs(x-center)>6.5;if(outside){x=clamp(x,center-7.6,center+7.6);vx*=-.28}let goal=outside?12:27;speed+=(goal-speed)*Math.min(1,dt*1.5);z=Math.min(selected.length,z+speed*dt);for(let o of obstacles){if(!o.hit&&Math.abs(z-o.z)<1.6&&Math.abs(x-o.x)<o.r+1){o.hit=true;speed=Math.max(8,speed*.32);collisions++;flash('CHOC ! - VITESSE');sound(165,.25)}}if(z>=selected.length)finish();$('timer').textContent=formatTime(elapsed);let p=Math.floor(z/selected.length*100);$('progress').textContent=p+'%';$('meter-fill').style.width=p+'%';$('speed').textContent=Math.round(speed);networkClock+=dt;if(room&&networkClock>.08){networkClock=0;try{sendState({x,z,course:selected.id,time:elapsed,playing:true})}catch{}}}
 if(toastUntil&&t>toastUntil){$('toast').classList.remove('visible');toastUntil=0}
 if(state==='menu'||state==='lobby'){let fly=(t*.013)%210;let pz=fly;updateBoatPosition(boatGroup,path(pz)+Math.sin(t*.001)*.8,pz,Math.sin(t*.002)*.05);let ideal=new THREE.Vector3(path(pz)+11,groundY(pz)+15,pz-18);camera.position.lerp(ideal,Math.min(1,dt*1.2));camera.lookAt(path(pz),groundY(pz),pz+15)}else{updateBoatPosition(boatGroup,x,z,-vx*.014);let target=new THREE.Vector3(x+8,groundY(z)+11,z-17);camera.position.lerp(target,Math.min(1,dt*5));camera.lookAt(x+vx*.1,groundY(z),z+12)}
 for(let [peerId,obj] of remoteBoats){obj.group.position.lerp(new THREE.Vector3(obj.x,groundY(obj.z)+.1,obj.z),Math.min(1,dt*10));obj.group.visible=obj.course===selected.id&&Math.abs(obj.z-(state==='menu'?0:z))<130}
 renderer.render(scene,camera)}
function randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
function peerRow(){let list=[`<div class="player-row"><span class="player-icon">◆</span><span>Toi <small>${state==='running'?'EN COURSE':'CONNECTÉ'}</small></span></div>`];for(let [id,p] of peers)list.push(`<div class="player-row"><span class="player-icon alt">◆</span><span>Joueur ${id.slice(0,4).toUpperCase()} <small>${p.course===selected.id?'CONNECTÉ':'AUTRE PISTE'}</small></span></div>`);$('players').innerHTML=list.join('')}
function leaveRoom(){if(room){room.leave();room=null}sendState=sendFinish=sendHello=null;peers.clear();for(let b of remoteBoats.values())scene.remove(b.group);remoteBoats.clear();$('online-label').textContent='PRÊT À GLISSER';$('lobby-status').textContent='Aucun salon rejoint';$('copy-link').classList.add('hidden');$('race-together').classList.add('hidden')}
function join(){let code=$('room-code').value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);if(code.length<4){$('lobby-status').textContent='Entre au moins 4 caractères pour le code.';return}leaveRoom();roomId=code;$('room-code').value=code;try{room=joinRoom({appId:'blockboat-3d-v1-nylann'},`race-${code}-${selected.id}`,{onJoinError:err=>{$('lobby-status').textContent='Connexion impossible. Réessaie plus tard.';console.warn(err)}});let stateAction=room.makeAction('move'),finishAction=room.makeAction('finish'),helloAction=room.makeAction('hello');sendState=stateAction.send;sendFinish=finishAction.send;sendHello=helloAction.send;room.onPeerJoin=id=>{peers.set(id,{course:selected.id});let ghost=createBoat('#ec728a');remoteBoats.set(id,{group:ghost,x:path(0),z:0,course:selected.id});scene.add(ghost);peerRow();$('lobby-status').textContent=`SALON ${code} · ${peers.size+1} JOUEUR${peers.size?'S':''}`;sendHello({course:selected.id,playing:state==='running',x,z},{target:id})};room.onPeerLeave=id=>{peers.delete(id);let b=remoteBoats.get(id);if(b)scene.remove(b.group);remoteBoats.delete(id);peerRow();$('lobby-status').textContent=`SALON ${code} · ${peers.size+1} JOUEUR${peers.size?'S':''}`};stateAction.onMessage=(data,{peerId})=>{let b=remoteBoats.get(peerId);if(!b||!Number.isFinite(data.x)||!Number.isFinite(data.z))return;b.x=clamp(data.x,-100,100);b.z=clamp(data.z,0,selected.length);b.course=data.course};helloAction.onMessage=(data,{peerId})=>{peers.set(peerId,{course:data.course});peerRow()};finishAction.onMessage=(data,{peerId})=>{if(data.course===selected.id&&Number.isFinite(data.time)){flash(`JOUEUR ${peerId.slice(0,4).toUpperCase()} : ${formatTime(data.time)}`);let entry=document.createElement('div');entry.className='finish-entry';entry.textContent=`${peerId.slice(0,4).toUpperCase()} · ${formatTime(data.time)}`;$('finishers').append(entry)}};$('lobby-status').textContent=`SALON ${code} · 1 JOUEUR · EN ATTENTE D'AMIS`;$('online-label').textContent='SALON '+code;$('copy-link').classList.remove('hidden');$('race-together').classList.remove('hidden');history.replaceState(null,'',`?course=${selected.id}&room=${code}`);peerRow()}catch(err){console.warn(err);$('lobby-status').textContent='Connexion impossible. Réessaie plus tard.'}}
renderCourses();init3D();requestAnimationFrame(animate);
$('play').onclick=()=>{leaveRoom();countdownStart()};$('multiplayer').onclick=()=>{state='lobby';show('lobby');$('room-code').value=initialRoom||randomCode();peerRow()};$('back-lobby').onclick=()=>{leaveRoom();resetMenu()};$('random-room').onclick=()=>{$('room-code').value=randomCode()};$('join-room').onclick=join;$('room-code').onkeydown=e=>{if(e.key==='Enter')join()};$('copy-link').onclick=async()=>{let url=location.href;try{await navigator.clipboard.writeText(url);$('copy-link').textContent='LIEN COPIÉ ✓';setTimeout(()=>$('copy-link').textContent='COPIER LE LIEN ⧉',1800)}catch{$('lobby-status').textContent=url}};$('race-together').onclick=countdownStart;
$('pause').onclick=()=>{if(state==='running'){state='paused';show('pause-panel')}};$('resume').onclick=()=>{state='running';show('hud');lastTime=performance.now()};$('quit').onclick=resetMenu;$('retry').onclick=countdownStart;$('home').onclick=resetMenu;$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'♪':'♫';$('sound').setAttribute('aria-label',muted?'Activer le son':'Couper le son');sound(620)};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a'||e.key.toLowerCase()==='q')held.left=true;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')held.right=true;if(e.key==='Escape'){if(state==='running')$('pause').click();else if(state==='paused')$('resume').click()}});window.addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a'||e.key.toLowerCase()==='q')held.left=false;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')held.right=false});window.addEventListener('blur',()=>{held.left=held.right=false});for(let [id,dir] of [['left','left'],['right','right']]){let b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();held[dir]=true;b.setPointerCapture(e.pointerId)});for(let event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>held[dir]=false)}
if(initialRoom){$('multiplayer').click();join()}
